# =============================================
# springboot configurations
# ---------------------------------------------
spring:
  application:
    name: ${OPENSHIFT_APP_NAME:database-connector-ods}
  datasource:  
         driver-class-name: oracle.jdbc.OracleDriver
         url: ${DATABASE_CONN_URL}
         username: ${DATABASE_CONN_USERNAME}
         password: ${DATABASE_CONN_PASSWORD}
         type: ${DATABASE_CONN_POOL_TYPE}
         oracleucp:
           connection-factory-class-name: oracle.jdbc.pool.OracleDataSource
           connection-pool-name: ${DBCONNECTOR_POOL:DBConnectorPool}
           connection-wait-timeout: ${UCP_POOL_CONN_WAIT_TIMEOUT}
           max-idle-time: ${UCP_POOL_CONN_MAX_IDLE_TIME}
           abandoned-connection-timeout: ${UCP_POOL_CONN_ABANDONED_CONNECTION_TIMEOUT}
           inactive-connection-timeout: ${UCP_POOL_CONN_INACTIVE_CONNECTION_TIMEOUT}
           connection-harvest-trigger-count: ${UCP_POOL_CONN_CONNECTION_HARVEST_TRIGGER_COUNT}
           connection-harvest-max-count: ${UCP_POOL_CONN_CONNECTION_HARVEST_MAX_COUNT}
           login-timeout: ${UCP_POOL_CONN_LOGIN_TIMEOUT}
           initial-pool-size: ${UCP_POOL_CONN_INITIAL_POOL_SIZE}
           max-pool-size: ${UCP_POOL_CONN_MAX_POOL_SIZE}
           min-pool-size: ${UCP_POOL_CONN_MIN_POOL_SIZE}
#           sql-for-validate-connection: 'select * from dual'
           

server:
  address: 0.0.0.0
  port: 8085
            

# =============================================
# database connector configurations
# ---------------------------------------------
connector:
    database:
        name: odsdb
        api:
            basepath: api/connector/db/odsdb
        beans:
            implementationPath: connector.database.beans.impl
            
            dao:
                v1:
                    ODSDBImplclasspath: com.alahli.middleware.customer.dao.ODSDBConnectorImplDao
                    ODSDBAccImplclasspath: com.alahli.middleware.account.dao.ODSDBConnectorImplDao
                        
            impl:
                CallProcedureToGetPFADetails:
                    httpmethod: POST
                    v1: ${connector.database.beans.dao.v1.ODSDBImplclasspath}
                    
                GetCustomerMainInfo:
                    httpmethod: POST
                    v1: ${connector.database.beans.dao.v1.ODSDBImplclasspath} 
                    
                CallProcedureToGetCustAcctCumulativeBalance:
                    httpmethod: POST
                    v1: ${connector.database.beans.dao.v1.ODSDBAccImplclasspath}
   
              
        errors:
            databaseError:
                system: ODS
                timeout: 
                        errorNumber: 710
                        errorDescription: ${connector.database.errors.database-error.system} Time out
                        nativeError: TIMEOUT
                general:
                        errorNumber: 709
                        errorDescription: ${connector.database.errors.database-error.system} Application Error
                        nativeError: SQL_EXCEPTION                     
            applicationError:
                system: MW
                timeout:
                        errorNumber: 782
                        errorDescription: ${connector.database.errors.application-error.system} Time out
                        nativeError: TIMEOUT
                general:
                        errorNumber: 783
                        errorDescription: ${connector.database.errors.application-error.system} Application Error
                        nativeError: GENERAL_EXCEPTION                                                                                                                             
         
  
#        datasource:
#            odsdb:
#                driver-class-name: oracle.jdbc.OracleDriver
#                name: bancsDay
#                password: appworks202
#                type: oracle.ucp.jdbc.PoolDataSourceImpl
#                url: jdbc:oracle:thin:@//192.168.10.102:1521/orcl
#               username: c##appworks202
#                configuration:
#                    connection-factory-class-name: oracle.jdbc.pool.OracleDataSource
#                    connection-pool-name: dh_cordysdb
#                    initial-pool-size: 1
#                    max-pool-size: 1
#                    min-pool-size: 1
#                    sql-for-validate-connection: select * from dual
#                    type: oracle.ucp.jdbc.PoolDataSource    


# =============================================
# configstore api parameters
# ---------------------------------------------
#configStoreConnector:
#  apiKeyName: configstore
#  host: ${CONFIGSTORECONNECTOR_HOST}
#  port: 8080
#  contextPath: ${CONFIGSTORECONNECTOR_CONTEXTPATH} 
   
# =============================================
# EAI DB Connector api parameters
# ---------------------------------------------
#EAIDBConnector:
#  apiKeyName: eai 
#  host: ${EAIDBCONNECTOR_HOST}
#  contextPath: ${EAIDBCONNECTOR_CONTEXTPATH}
            
logging:
   config: classpath:logback-spring.xml
   componentType: ODSDB_CONNECTOR
   isloggingDisabled: ${IS_LOGGING_DISABLED:false}
   isAPIsLoggingDisabled:
      GetAccountTransactions: ${IS_API_LOGGING_DISABLED :false}
   APIsKeys:
#      GetAccountTransactions:
#         fields:
#          - accountId
#          - transactionType
#         fieldsJsonPath:
#            accountId: AccountTransactionsRequest.accountId
#            transactionType: AccountTransactionsRequest.transactionType  



camel:
  opentracing:
    enabled: ${JAEGER_TRACING_FLAG:false}
  servlet:
    mapping:
      context-path: /*
  
JAEGER_SAMPLER_PARAM: 1.0
JAEGER_SAMPLER_TYPE: const
JAEGER_SERVICE_NAME: ${JAEGER_SERVICE_NAME:ODSDB_CONNECTOR}
JAEGER_ENDPOINT: ${JAEGER_ENDPOINT}    

# Its a temp property to know the envirnoment test: DH and live: SNB
testRegion:
 name: ${TESTING_REGION_VALUE:test} 
    
    
